作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [2]:
import numpy as np

In [3]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [4]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?np.amax(english_score)
eng_mean=np.mean(english_score)
math_mean=np.nanmean(math_score)
ch_mean=np.mean(chinese_score)
print(f'english平均值:{eng_mean}')
print(f'math平均值:{math_mean}')
print(f'chinese平均值:{ch_mean}')
print("==============================")
#最大值
eng_max=np.amax(english_score)
math_max=np.nanmax(math_score)
ch_max=np.amax(chinese_score)
print(f'english最大值:{eng_max}')
print(f'math最大值:{math_max}')
print(f'chinese最大值:{ch_max}')
print("==============================")
#最小值
eng_min=np.amin(english_score)
math_min=np.nanmin(math_score)
ch_min=np.amin(chinese_score)
print(f'english最小值:{eng_min}')
print(f'math最小值:{math_min}')
print(f'chinese最小值:{ch_min}')
print("==============================")
#標準差
eng_std=np.std(english_score)
math_std=np.nanstd(math_score)
ch_std=np.std(chinese_score)
print(f'english標準差:{eng_std}')
print(f'math標準差:{math_std}')
print(f'chinese標準差:{ch_std}')


english平均值:67.16666666666667
math平均值:66.6
chinese平均值:75.33333333333333
english最大值:89
math最大值:85.0
chinese最大值:90
english最小值:48
math最小值:60.0
chinese最小值:65
english標準差:13.433995020924426
math標準差:9.707728879609279
chinese標準差:8.825468196582484


In [5]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[-2]=55
print(math_score)
math_mean=np.mean(math_score)
math_max=np.amax(math_score)
math_min=np.min(math_score)
math_std=np.std(math_score)
print(f'math平均值:{math_mean}')
print(f'math最大值:{math_max}')
print(f'math最小值:{math_min}')
print(f'math標準差:{math_std}')




[60. 85. 60. 68. 55. 60.]
math平均值:64.66666666666667
math最大值:85.0
math最小值:55.0
math標準差:9.860132971832694


In [6]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
# 兩個行向量拼接到一起，形成一個2*6的矩陣
chinese_english = np.r_[chinese_score, english_score].reshape(2,6)
chinese_math = np.r_[chinese_score, math_score].reshape(2,6)
print(chinese_english)
print(chinese_math)

c_c_e = np.corrcoef(chinese_english)[0,1]
print(f'chinese_english相關係數:{c_c_e}')
c_c_m = np.corrcoef(chinese_math)[0,1]
print(f'chinese_math相關係數:{c_c_m}')
if c_c_e > c_c_m:
    print("國文成績相關係數最高的學科是英文")
else:
    print("國文成績相關係數最高的學科是數學")


[[65 90 82 72 66 77]
 [55 89 76 65 48 70]]
[[65. 90. 82. 72. 66. 77.]
 [60. 85. 60. 68. 55. 60.]]
chinese_english相關係數:0.9779282830211268
chinese_math相關係數:0.740568027023363
國文成績相關係數最高的學科是英文


In [63]:
# x是一個行向量
x = np.array([1, 3, 564, 675, 6567]).reshape(1, -1)
print(x)

# y1、y2都是行向量
y1 = np.array([1, 3, 555555, 675, 6567]).reshape(1, -1)
y2 = 2*x+4

# 兩個行向量拼接到一起，形成一個兩行的矩陣
x_y1 = np.r_[x, y1]
x_y2 = np.r_[x, y2]
print(x_y1)
print(x_y2)

# 注意使用np.corrcoef求相關係數時
# 求取得到的是任意兩行的相關係數構成的相關係數矩陣
# 所以一定要把想求的兩個向量分別放在不同的行，而不是列
c_x_y1 = np.corrcoef(x_y1)[0, 1]
print(c_x_y1)

# 由於y2 = 2*x+4，相關係數c_x_y2必定等於1
c_x_y2 = np.corrcoef(x_y2)[0, 1]
print(c_x_y2)

[[   1    3  564  675 6567]]
[[     1      3    564    675   6567]
 [     1      3 555555    675   6567]]
[[    1     3   564   675  6567]
 [    6    10  1132  1354 13138]]
-0.18724527057600632
1.0
